version: "3"
services:
  postgis:
    image: pgrouting/pgrouting
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=frank
      - POSTGRES_PASSWORD=atxroutes
volumes:
  db-data: